sudo: false
language: python
python:
 - 2.7
 - 3.5
install:
 - python install.py
 - source python-virtualenv/bin/activate
script:
 - python setup.py polysquarelint --exclusions=*/venv/*,*/node_modules/*,*/dist/*,*/public/components/* --suppress=codes=I100,LongDescription
 - python setup.py green
